name: Echo Secret Example
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  show-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Echo secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: echo "Hello $MY_SECRET"
