name: Echo Secret Example
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  show-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Echo secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: echo "Hello $MY_SECRET"
      - name: Check if secret exists
        run: |
          if [ -z "${{ secrets.MY_SECRET }}" ]; then
            echo "Secret is not set"
            exit 1
          else
            echo "Secret is configured"
          fi
